#!/bin/sh
# shellcheck source=./config.def

# A post-receive hook to form stagit pages,
# creating tarballs, reinitializing stagit-index.
#
# This script can be run for each repository, without
# pushing, by going to the repository directory and
# running 'hooks/post-receive'.

# Parse the configuration file
hooksdir=$(readlink -f "$0") hooksdir=${hooksdir%/*}
. "$hooksdir/config"
. "$hooksdir/lib"

# Store the repository name in a variable. We strip
# the directory names and '.git' here.
repository=${PWD##*/} repository=${repository%.git}
repository_path=${PWD}

# Push to mirrors if a 'mirrors' file exists on the
# base directory.
[ -f mirrors ] && while read -r mirror; do
    git push --mirror "$mirror"
done < mirrors

# Generate files parsed by 'stagit'.
[ -f owner ] || printf '%s\n' "$OWNER" > owner
[ -f url   ] || printf '%s\n' "$BASE_URL/$repository" > url

# Make sure we export the current repository.
# No, we don't want to run the 'export' command.
# shellcheck disable=2238
:> export

# Create the stagit structure
mkdir -p "$STAGIT_DIR/$repository"

# Generate the index for every exported repository
set --
for repo in "$REPO_DIR/"*/export; do set -- "$@" "${repo%/*}"; done
stagit-index "$@" > "$STAGIT_DIR/index.html"

# Install style files
[ "$CSS" ]     && install -Dm644 "$CSS"     "$STAGIT_DIR/style.css"
[ "$LOGO" ]    && install -Dm644 "$LOGO"    "$STAGIT_DIR/logo.png"
[ "$FAVICON" ] && install -Dm644 "$FAVICON" "$STAGIT_DIR/favicon.png"

(
cd "$STAGIT_DIR/$repository" || return 1

# We create a cache to the .cache file so log creation
# is faster on larger repositories.
stagit -c .cache "$repository_path"

for file in style.css logo.png favicon.png; do
    [ -f "../$file" ] && ln -sf "../$file" "$file"
done

# Link index.html to log.html so users don't have to
# type the whole file out.
ln -sf log.html index.html
)


# Create archives and plain raw files
[ "$ARCHIVE_ALL" = 1 ] || [ -f archive ] && {
    mkdir -p "$STAGIT_DIR/archive/$repository"
    git show-ref --tags --heads |
        while read -r _ ref; do
            tag=${ref#refs/*/}
            tarball="$STAGIT_DIR/archive/$repository/$repository-$tag.tar.gz"

            # Unless we are working with a branch, skip recreation of a tarball.
            [ "${ref##refs/heads/*}" ] && [ -f "$tarball" ] && continue

            git archive \
                --format tar.gz \
                --prefix "$repository-$tag/" \
                -o "$tarball" \
                -- "$tag"
        done
    for dir in archive "archive/$repository"; do (
        cd "$STAGIT_DIR/$dir" || exit 1
        lsindex "$STAGIT_DIR" > index.html
    ) done
}

[ "$RAW_ALL" = 1 ] || [ -f raw ] && {
    git show-ref --heads |
        while read -r _ ref; do
            branch=${ref##*/}
            mkdir -p "$STAGIT_DIR/raw/$repository/$branch"
            git archive --format tar -- "$branch" |
                (cd "$STAGIT_DIR/raw/$repository/$branch" || return 1 ; tar xf -)
        done
}
